### ISSUE TITLE
PGNs 129283, 129284, 129285: Navigation stuff

### ISSUE THREAD

**Issue by tkurki** [SignalK/n2k-signalk#11]
Add support for 

129283: Cross Track Error
{"timestamp":"2015-01-15-16:25:14.978","prio":"3","src":"4","dst":"255","pgn":"129283","description":"Cross Track Error","fields":{"SID":"250","Navigation Terminated":"No"}}

129284: Navigation Data
{"timestamp":"2015-01-15-16:25:15.186","prio":"3","src":"4","dst":"255","pgn":"129284","description":"Navigation Data","fields":{"SID":"250"}}

129285: Navigation - Route/WP Information
{"timestamp":"2015-01-15-16:25:12.644","prio":"7","src":"4","dst":"255","pgn":"129285","description":"Navigation - Route/WP Information","fields":{"nItems":"2","Navigation direction in route":"1","Supplementary Route/WP data available":"0","Reserved":"0","Reserved":"0","WP ID":"0","WP ID 2":"1"}}

**Comment by lfrancois** [comment]
I was going through the PGNs available on my boat and not recognized by n2k-analyzer and I have one here, not vital for me. So very low priority.

*129285 Navigation - Route/WP Information*

```
1969-12-31-16:00:01,481 0   4 255 129285 Navigation - Route/WP Information:  Start RPS# = Unknown; nItems = 2; Database ID = Unknown; Route ID = Unknown; Navigation direction in route = Unknown; Supplementary Route/WP data available = 1

```

```
{"timestamp":"1969-12-31-16:00:01,481","prio":0,"src":4,"dst":255,"pgn":129285,"description":"Navigation - Route/WP Information","fields":{"nItems":2,"Supplementary Route/WP data available":1,"list":[{}]}}```

**Comment by sbender9** [comment]
These are all done.
