### ISSUE TITLE
PGNs 129539,129540: GNSS

### ISSUE THREAD

**Issue by tkurki** [SignalK/n2k-signalk#12]
129539: GNSS DOP

```
{
  "timestamp": "2015-01-15-16:17:30.684",
  "prio": "6",
  "src": "2",
  "dst": "255",
  "pgn": "129539",
  "description": "GNSS DOPs",
  "fields": {
    "SID": "38",
    "Actual Mode": "3D",
    "HDOP": "0.80",
    "VDOP": "1.30",
    "TDOP": "327.67"
  }
} {
  "timestamp": "2015-01-15-16:17:31.421",
  "prio": "6",
  "src": "245",
  "dst": "255",
  "pgn": "129539",
  "description": "GNSS DOPs",
  "fields": {
    "SID": "151",
    "Desired Mode": "Auto",
    "Actual Mode": "3D",
    "HDOP": "0.79",
    "VDOP": "1.59",
    "TDOP": "1.00"
  }
}
```

129540: GNSS Sats in View

```
{
  "timestamp": "2014-08-15T19:00:00.878",
  "prio": 6,
  "src": 160,
  "dst": 255,
  "pgn": 129540,
  "description": "GNSS Sats in View",
  "fields": {
    "SID": 207,
    "Sats in View": 11,
    "list": [
      {
        "PRN": 32,
        "Elevation": 69,
        "Azimuth": 223,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 1,
        "Elevation": 66,
        "Azimuth": 268,
        "SNR": 29,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 11,
        "Elevation": 61,
        "Azimuth": 207,
        "SNR": 36,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 14,
        "Elevation": 46,
        "Azimuth": 70,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 20,
        "Elevation": 27,
        "Azimuth": 252,
        "SNR": 28,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 17,
        "Elevation": 21,
        "Azimuth": 319,
        "SNR": 17,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 22,
        "Elevation": 19,
        "Azimuth": 81,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 4,
        "Elevation": 18,
        "Azimuth": 295,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 19,
        "Elevation": 16,
        "Azimuth": 186,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 28,
        "Elevation": 10,
        "Azimuth": 283,
        "SNR": 32,
        "Range residuals": 0,
        "Status": "Used"
      },
      {
        "PRN": 24,
        "Elevation": 8,
        "Azimuth": 10,
        "SNR": 22,
        "Range residuals": 0,
        "Status": "Used"
      }
    ]
  }
}
```

**Comment by canboat** [comment]
Fixed in CANboat now, so I guess your code will get the array immediately as well.

**Comment by lfrancois** [comment]
*129539 GNSS DOPs*

Still didn't make it through n2k-signalk

```1969-12-31-16:00:01,482 0   1 255 129539 GNSS DOPs:  SID = 10; Desired Mode = Unknown; Actual Mode = 3D; HDOP = 0.70; VDOP = 1.30; TDOP = 327.67```

```{"timestamp":"1969-12-31-16:00:01,482","prio":0,"src":1,"dst":255,"pgn":129539,"description":"GNSS DOPs","fields":{"SID":10,"Actual Mode":"3D","HDOP":0.70,"VDOP":1.30,"TDOP":327.67}}```

**Comment by tkurki** [comment]
https://github.com/SignalK/n2k-signalk/blob/master/test/todo.txt#L32-L37

**Comment by davidsanner** [comment]
Seems mapping the list of each tracked satellite in "129540: GNSS Sats in View" PGN is rather involved (still looking into it) but might it be a good start to map the single "Sats in View" value to navigation.gnss.satellites?  I'd be happy to do a PR for 129540.js PGN?  This is working well.

module.exports = [
  {
    source: 'Sats in View',
    node: 'navigation.gnss.satellites'
  }
]

However realizing there is no way to have SK source priorities choose based on source and PGN so two competing PGNs from the same source will flip back and forth (eg. Sats in View 129029 & 129540) maybe we'd need that first?

**Comment by Hakansv** [comment]
Please..
Add the PGP 129540 PR. 
OpenCPN does miss [navigation.gnss.satellitesInView] data when using a N2k GNSS receiver via SK.

And..
The "number of Sats" in use from PGP 129029 (pos 12) and used for [navigation.gnss.satellites] is probably not the same as "Sats in View" from 129540 what would be used for [navigation.gnss.satellitesInView]
Compared to NMEA0183 is 
"number of sats" the "satellites in use" from GPGGA: what's used for the fix calculation.
"sats in view" how many satellites are seen from GPGSV.  
See also [NMEA0183->SK](https://github.com/SignalK/nmea0183-signalk/blob/cae73b0166c4a21cf7948bbfd8dd946e54b371e1/hooks/GSV.js#L131)

**Comment by Hakansv** [comment]
Here's a fresh content of the PGP 129540 for comparison. See picture:
Up to 12 satellites data are shown. Only field "0" is evolved. 1-11 looks the same.
For raw data see further down.

![bild](https://user-images.githubusercontent.com/7202854/158633544-49ed4ca3-749d-4f2b-a18d-fef1b55c8af5.png)

`129540":{"canId":435815551,"prio":6,"src":127,"dst":255,"pgn":129540,"timestamp":"2022-03-15T08:54:32.611Z","input":[],"fields":{"SID":0,"Sats in View":12,"list":[{"PRN":1,"Elevation":0.2268,"Azimuth":0.48860000000000003,"SNR":37,"Range residuals":0,"Status":"Used"},{"PRN":10,"Elevation":0.4188,"Azimuth":5.218500000000001,"SNR":32,"Range residuals":0,"Status":"Used"},{"PRN":12,"Elevation":0.48860000000000003,"Azimuth":3.8920000000000003,"SNR":25,"Range residuals":0,"Status":"Used"},{"PRN":13,"Elevation":0.3839,"Azimuth":2.7576,"SNR":43,"Range residuals":0,"Status":"Used"},{"PRN":14,"Elevation":0.34900000000000003,"Azimuth":1.0471000000000001,"SNR":46,"Range residuals":0,"Status":"Used"},{"PRN":15,"Elevation":0.6806,"Azimuth":3.351,"SNR":41,"Range residuals":0,"Status":"Used"},{"PRN":17,"Elevation":0.733,"Azimuth":1.3962,"SNR":49,"Range residuals":0,"Status":"Used"},{"PRN":19,"Elevation":0.6806,"Azimuth":1.9722000000000002,"SNR":44,"Range residuals":0,"Status":"Used"},{"PRN":21,"Elevation":0.1396,"Azimuth":0,"SNR":26,"Range residuals":0,"Status":"Used"},{"PRN":23,"Elevation":0.34900000000000003,"Azimuth":4.607600000000001,"SNR":25,"Range residuals":0,"Status":"Used"},{"PRN":24,"Elevation":1.2042000000000002,"Azimuth":4.625100000000001,"SNR":48,"Range residuals":0,"Status":"Used"},{"PRN":74,"Elevation":0.925,"Azimuth":1.1344,"SNR":48,"Range residuals":0,"Status":"Used"},{"SNR":2.5500000000000003}]},"description":"GNSS Sats in View"}},"productName":"GS25        Antenna","hardwareVersion":"","softwareVersion":"01100_E 1400 TB102512_10","productID":6829,"serialNumber":"100298#","nmea2000Version":1111,"certificationLevel":1,"loadEquivalency":1}},`

**Comment by tkurki** [comment]
@davidsanner feel like digging into this one?

**Comment by tkurki** [comment]
Published in v2.5.0 @Hakansv let me know how it works.

**Comment by Hakansv** [comment]
@tkurki 
Thanks. I'm on a job. Will test when home again.

**Comment by davidsanner** [comment]
@tkurki - I had started this but your code is cleaner & completed.  I tested yesterday & again today - looks good.  Nice to have the n2k working to compliment 0183/GSV data.  (GSV support in signalk-nmea0183 would complete.)

**Comment by Hakansv** [comment]
@tkurki 
Now home and the MCS board in order: Yes it works as expected.
I've copied your new files into my environment and connected a GNSS receiver. See pict 1.
Also corresponding code in OCPN is thus now working, se pict 2.
So I think this change can be included in next SK released.
Many thanks
Håkan
![bild](https://user-images.githubusercontent.com/7202854/162043659-855a08dc-f435-4236-99d9-8a7e45beb00b.png)
![bild](https://user-images.githubusercontent.com/7202854/162044078-3c8a3633-5894-4b68-b9b0-4e66a2864e31.png)
