### ISSUE TITLE
PGN 130842: Simnet AIS Class B static data

### ISSUE THREAD

**Issue by tkurki** [SignalK/n2k-signalk#15]
See http://yachtelectronics.blogspot.fi/2012_11_01_archive.html

130842: Simnet: AIS Class B static data (msg 24 Part A)
130842: Simnet: AIS Class B static data (msg 24 Part B)
{"timestamp":"2015-01-15-16:17:15.843","prio":"6","src":"43","dst":"255","pgn":"130842","description":"Simnet: AIS Class B static data (msg 24 Part A)","fields":{"Manufacturer Code":"Simrad","Industry Code":"Marine","Message ID":"Msg 24 Part A","Repeat indicator":"Second retransmission","E":"24","User ID":"367479480","Name":"SUMMER WIND"}}
{"timestamp":"2015-01-15-16:17:17.962","prio":"6","src":"43","dst":"255","pgn":"130842","description":"Simnet: AIS Class B static data (msg 24 Part B)","fields":{"Manufacturer Code":"Simrad","Industry Code":"Marine","Message ID":"Msg 24 Part B","Repeat indicator":"Second retransmission","E":"24","User ID":"367479480","Type of ship":"Sailing","Vendor ID":"COMNAV","Callsign":"WDF6945","Length":"13.0","Beam":"4.0","Position reference from Starboard":"2.0","Position reference from Bow":"6.0","Mothership User ID":"0","":"0","Spare":"48"}}
{"timestamp":"2015-01-15-16:17:16.283","prio":"6","src":"3","dst":"255","pgn":"130842","description":"Unknown PGN","fields":{ "Manufacturer Code": "Simrad","Industry Code":"Marine"}}

**Comment by sbender9** [comment]
There now

**Comment by timmathews** [comment]
Should this be in a simnet directory since it's a proprietary PGN?
