### ISSUE TITLE
Extend support for other PGN 130314 pressure sources

### ISSUE THREAD

**Issue by jncarter123** [SignalK/n2k-signalk#164]
Currently PGN 130314 is supported for atmospheric pressure. The PGN also supports the following pressure sources: 1=Water, 2=Steam, 3=Compressed Air, 4=Hydraulic. There are many uses for these like steering, bow thrusters, etc. As another example I'm using a couple of water pressure sensors for my watermaker boost and main pressures. I'm not certain where this would fit in the existing schema? Perhaps something generic and then people could use pathmapper plugin to customize for their use case?

**Comment by tkurki** [comment]
Sounds a reasonable course of action. Do you happen to have any sample data available?

**Comment by jncarter123** [comment]
Sorry I had been traveling and just got a chance to run the watermaker. 

`pi@raspberrypi:~/ydraw2 $ nc 192.168.51.20 1457 | grep 15FD0A58
16:01:11.485 R 15FD0A58 C3 02 01 15 53 20 00 FF
16:01:11.486 R 15FD0A58 C3 03 01 FF FF FF 7F FF
16:01:27.487 R 15FD0A58 CB 03 01 FF FF FF 7F FF
16:02:41.486 R 15FD0A58 F0 02 01 D2 05 20 00 FF
16:02:41.487 R 15FD0A58 F0 03 01 FF FF FF 7F FF
16:03:21.484 R 15FD0A58 09 02 01 57 EC 1F 00 FF
16:03:21.485 R 15FD0A58 09 03 01 FF FF FF 7F FF
16:03:29.484 R 15FD0A58 0D 03 01 FF FF FF 7F FF
16:14:23.468 R 15FD0A58 59 03 01 FF FF FF 7F FF
16:15:53.465 R 15FD0A58 86 03 01 FF FF FF 7F FF
16:15:59.565 R 15FD0A58 89 02 01 62 9D 1D 00 FF
16:15:59.566 R 15FD0A58 89 03 01 FF FF FF 7F FF
16:16:35.467 R 15FD0A58 9B 03 01 FF FF FF 7F FF
16:17:11.564 R 15FD0A58 AD 03 01 FF FF FF 7F FF
16:18:05.564 R 15FD0A58 C8 02 01 A4 36 1D 00 FF
16:18:05.565 R 15FD0A58 C8 03 01 FF FF FF 7F FF




{"canId":368904792,"prio":5,"src":88,"dst":255,"pgn":130314,"direction":"R","time":"16:27:53.550","fields":{"SID":243,"Instance":2,"Source":"Water","Pressure":180911.6},"description":"Actual Pressure","timestamp":"2020-02-12T16:27:54.012Z"}
{"canId":368904792,"prio":5,"src":88,"dst":255,"pgn":130314,"direction":"R","time":"16:27:53.551","fields":{"SID":243,"Instance":3,"Source":"Water","Pressure":214748364.7},"description":"Actual Pressure","timestamp":"2020-02-12T16:27:54.014Z"}
`

There are two sources. Instance 2 is the low pressure boost pump and was running around 25-30 psi when I captured this. Instance 3 is the high pressure main pump and is not yet connected to the watermaker.

**Comment by jncarter123** [comment]
@tkurki Let me know what you think. I took a look at the code and more or less copied the logic used for temperature. The current paths are <source>.<index>.pressure, ex. water.3.pressure. I tried thinking of a common path suffix to use, but wasn't certain what if anything to use.
