### ISSUE TITLE
Rename to signalk-parser-nmea2000

### ISSUE THREAD

**Issue by timmathews** [SignalK/n2k-signalk#18]
Should we rename this to signalk-parser-nmea2000 to match the signalk-* naming convention and be more consistent with signalk-parser-nmea0183?

**Comment by rob42** [comment]
yes probably

**Comment by tkurki** [comment]
The npm package names for these two modules  are n2k-signalk and nmea0183-signalk. This is what you see in code and under node_modules in the file system. I would **much ** rather rename nmea0183 parser repo to match this nice, concise module name.
