### ISSUE TITLE
Is it possible to add custom meta in a mapper?

### ISSUE THREAD

**Issue by fabdrol** [SignalK/n2k-signalk#187]
E.g.

```javascript
{
  node: (n2k) => `electrical.battery.${instance(n2k)}.someValue`,
  value: (n2k) => n2k.fields['Some Value'],
  meta: (n2k) => {
    return { someMetaProp: "value" }
  }
}
```

The return value from `meta()` will be added to the meta long the way.

**Comment by sbender9** [comment]
It would take some work on the server side to make that possible...

**Comment by tkurki** [comment]
Meta deltas?

**Comment by fabdrol** [comment]
@tkurki is anyone still talking about those?

**Comment by tkurki** [comment]
Me and Scott. As usual. 

There’s a clear use case, just haven’t had the juice to pull it to something useful.

**Comment by sbender9** [comment]
I've resurrected my old server PR for meta deltas. https://github.com/SignalK/signalk-server-node/pull/481

I'll look at n2k-signalk changes next...

**Comment by fabdrol** [comment]
> As usual.
Not sure how constructive that is @tkurki 

Anyhow, anything I can do to help - for instance work on n2k-signalk @sbender9 ?

**Comment by sbender9** [comment]
Yeah, that would help. Basically need changes to n2kMapper.js to look for meta like in your example and add it to the generated delta.

**Comment by tkurki** [comment]
>Not sure how constructive that is

More a statement of fact than trying to be snide. Scott has been bugging me several times over the meta deltas and I have failed to contribute 😞 . Apart from that sporadic interest.

**Comment by tkurki** [comment]
So the answer is "yes in principle, by emitting meta deltas", somebody just needs to add a way to do that in n2k-signalk.
