### ISSUE TITLE
Question regarding AC power PGNs

### ISSUE THREAD

**Issue by fabdrol** [SignalK/n2k-signalk#189]
@sbender9 

A while back you implemented (maretron specific?) AC power PGNs. I was using a fork with a slightly different implementation. I recently tried to rebase to master, which broke a bunch of things for me. 

In your implementation, you actually retrieve a device ID (as specified by Signal K) for AC devices. In the tests, there is an ID that is used in the `path`, i.e: `electrical.ac.24.total.energyExport.value`

(see: https://github.com/SignalK/n2k-signalk/blob/master/test/maretron.js#L27)

However, looking at the data, it's unclear to me how that ID is constructed:

```json
{
   "canId":217968066,
   "prio":3,
   "src":194,
   "dst":255,
   "pgn":65005,
   "direction":"R",
   "time":"18:58:12.730",
   "fields":{
      "Total Energy Export":0,
      "Total Energy Import":0
   },
   "description":"Utility Total AC Energy",
   "timestamp":"2020-03-28T18:58:13.092Z"
}
```

Is that `24` the assigned ISO address? If so, how does that account for that address changing?

**Comment by sbender9** [comment]
This is the “Device Instance” it comes from the ISO address claim.

**Comment by fabdrol** [comment]
Ah okay, and that's configured and fixed?

**Comment by sbender9** [comment]
Yeah, configured by the user/installer (I think the method may differ by manufacturer). It does not change.
