### ISSUE TITLE
PGN 130312 Deprecated. Long live 130316?

### ISSUE THREAD

**Issue by anhorbc** [SignalK/n2k-signalk#205]
Could someone please add support for PGN 130316, since PGN 130312 has been deprecated a few years now?

**Comment by davidsanner** [comment]
To avoid confusion/duplication I think only one of these should be supported.  I'd be happy to generate a PR for the conversion to 130316 but might this break older n2k devices that only support 130312?  Flip side, are new devices still decoding 130312 ?

Also not sure if the different instance numbers (eg.  101, 102) for different measurements map cleanly?

**Comment by tkurki** [comment]
130316 added in #234
