### ISSUE TITLE
127506 defined as single packet, when it is actually a fast packet

### ISSUE THREAD

**Issue by nmbath** [SignalK/n2k-signalk#221]
The PGN127506 is defined as a single packet, when it is actually a fast packet of I believe 11 bytes.

  can1  19F21229   [8]  60 0B F7 00 00 60 FF FF
  can1  19F21229   [8]  61 FF FF FF 90 01 FF FF

  can1  19F21229   [8]  80 0B 0D 00 00 60 FF FF
  can1  19F21229   [8]  81 FF FF FF 90 01 FF FF

There is also an 8th field for Amp Hours consumed.

I believe the attached diff is what needs to be applied to address this.

I have posted an issue to the canboat repository as well, as that needs fixing as well.l 

[127506.js.diff.zip](https://github.com/SignalK/n2k-signalk/files/6884058/127506.js.diff.zip)

![image](https://user-images.githubusercontent.com/73959588/127123984-882d3bf7-af91-45fc-b1e8-059d32027157.png)

**Comment by tkurki** [comment]
The fix should happen at https://github.com/canboat/canboat/issues/244 and then here.

**Comment by keesverruijt** [comment]
Fixed in Canboat. Note that @nmbath showed that a new field has been added, taking the PGN to 11 bytes. Also note the really _terrible_ name of this field, "Amp Hours", which is stored in AmpHours but shown in Coulombs. It should have been a four byte field in Coulombs, really.

**Comment by nmbath** [comment]
The following diff to /@signalk/n2k-signalk/pgns/127506.js adds the Amp Hours field as dischargeSinceFull.

40,41c40
<   }, 
<   {
---
>   } /*, {
46,52c45
<   },
<   {
<     source: 'Amp Hours',
<     node: function (n2k) {
<       return 'electrical.batteries.' + instance(n2k) + '.capacity.dischargeSinceFull'
<     }
<   }
---
>   } */

Please could this be added

**Comment by nmbath** [comment]
Any progress on this?

**Comment by tkurki** [comment]
i assume this was handled at https://github.com/canboat/canboatjs/issues/162 and in any case a canboat(js) matter, not n2k-signalk.
