### ISSUE TITLE
130606 decodes to wind.directionGround - not in the spec

### ISSUE THREAD

**Issue by wellenvogel** [SignalK/n2k-signalk#236]
N2K pgn 130606 with reference 'True (ground referenced to North)' is decoded to environment/wind/directionGround.
But this is not according to the signalK spec (easily can be seen as there is no unit meta data available in the data browser).
Shouldn't it decode to environment/wind/directionTrue?

**Comment by tkurki** [comment]
I just fixed this in 0183 and derived data. Can you PR a fix?

**Comment by wellenvogel** [comment]
ok, can do, Do you agree on directionTrue as the correct value?

**Comment by wellenvogel** [comment]
Hmm - nice  has already been corrected with #230.
So I guess we can close this one.

**Comment by tkurki** [comment]
Oops, sorry, my mistake between 0183 and n2k 🤦 .....
