### ISSUE TITLE
PGN 127503 & 127504 not included in pgns/index.js

### ISSUE THREAD

**Issue by patg** [SignalK/n2k-signalk#251]
Ist there any reason why those PGNs are not included index.js ?
The source code for the PGNs is present in the source tree (127503.js and 127504.js) and the
data seems correct.

Reference: https://www.nmea.org/Assets/nmea-2000-corrigendum-1-2010-1.pdf

**Comment by tkurki** [comment]
They were added in 2df6f754b0b04b9721c37b37269b006b1e7cd971 but to me it looks they were just accidentally left out, because all other pgns where added via maretron.js.

@sbender9 comments?

**Comment by sbender9** [comment]
Yeah, I think was a mistake. They should have been included (and tests)
