### ISSUE TITLE
PGN 129039 (AIS Class A position report) crashes SignalK Server

### ISSUE THREAD

**Issue by tvr256** [SignalK/n2k-signalk#268]
Load the N2K sample file aava-n2k.data.

The logs immediately fill up with a repeating error message:

[PGN 129039 error.txt](https://github.com/SignalK/n2k-signalk/files/14487714/PGN.129039.error.txt)

```
ERROR 2024-03-04T21:30:33.457Z [analyzer] PGN 129039: field "Reserved" print routine did not print anything

ERROR 2024-03-04T21:30:33.457Z [analyzer] PGN 129039 analysis error

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039: field "Reserved" print routine did not print anything

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039 analysis error

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039: field "Reserved" print routine did not print anything

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039 analysis error

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039: field "Reserved" print routine did not print anything

ERROR 2024-03-04T21:30:33.458Z [analyzer] PGN 129039 analysis error
```

After less than a minute the SignalK server appears to crash and restart. The web UI is temporarily unavailable, and then comes back with uptime 0 days 0 hours 0 minutes.

Reproducible on OpenPlotter 4 running on RPi 5. I don't remember seeing the issue on my previous installation (OpenPlotter 3 on RPi 4), so it could be the new hardware or a recent SignalK change?

@Sailoog @tkurki FYI

![image](https://github.com/SignalK/n2k-signalk/assets/117984987/1231dbdb-303e-4cd8-9a63-da53fbfffef4)

![image](https://github.com/SignalK/n2k-signalk/assets/117984987/7ae159c8-a1cb-44ab-8f07-9d0d8f9877ed)

**Comment by sbender9** [comment]
Any specific reason you using canboat instead of canboatjs?

**Comment by tvr256** [comment]
Wow @sbender9 , how did you spot that so quickly? Changed to "Actisense NMEA 2000 (canboatjs)" and it works perfectly. Thanks for the fix!

Closing due to user stupidity....
