### ISSUE TITLE
Two decades error in environment.outside.pressure conversion

### ISSUE THREAD

**Issue by aplathan** [SignalK/n2k-signalk#60]
Signal k makes a two decade (i.e., 100x) error in pressure conversion. 

Not sure if this is a bug in n2k-signalk or instrumentpanel, or some other module. It's visible in instrumentpanel, but I'm guessing unit conversions are originally made in the n2k-signalk module.

Original n2k message:
```
2017-05-06-15:00:26.000,5,130310,150,255,8,ff,ff,ff,ff,ff,f6,03,ff
```

Same message through analyzer:
```
2017-05-06-15:17:00.000 5 150 255 130310 Environmental Parameters:  SID = Unknown; Atmospheric Pressure = 1.014 bar (69.9 PSI)
```

[Pressure shown in instrumentpanel](https://www.dropbox.com/s/5setrzq292muxqk/Screenshot%202017-05-06%2020.17.01.png?dl=0)
```
10140000 Pa
10140 kPa
104 bar
```

**Comment by timmathews** [comment]
n2k-signalk is assuming that the value from analyzer is in hPa: https://github.com/SignalK/n2k-signalk/blob/master/pgns/130310.js#L15-L16, but analyzer was updated to always output SI units in JSON: https://github.com/canboat/canboat/commit/b11885c30beb65ae397dafdd11abd77669166106.

I think the conversion in n2k-signalk should be removed
