### ISSUE TITLE
Number of satellites (navigation.gnss.satellites) is shown with decimals

### ISSUE THREAD

**Issue by aplathan** [SignalK/n2k-signalk#61]
SK should use integers when reporting the number of satellites in view.

Analyzer outputs this correctly:
```
{"timestamp":"2017-05-06-15:25:50.000","prio":6,"src":1,"dst":255,"pgn":129540,"description":"GNSS Sats in View","fields":{"SID":149,"Mode":"2","Sats in View":12,"list":[{}]}}
```

but SK adds decimal, and shows this as 12.0 (at least in instrumentpanel and WilhelmSK): https://www.dropbox.com/s/lhh0a9mlhsj3f2u/Screenshot%202017-05-07%2020.10.17.png?dl=0

Interestingly rest api (http://localhost:3000/signalk/v1/api/) uses an integer:
```
{
satellites: {
value: 12,
$source: "n2kFromFile.1",
timestamp: "2017-05-06T15:13:17.000",
pgn: 129029
},
```
Note: My plotter sends this information in PGN 129540, but SK logs show PGN 129029.

**Comment by sbender9** [comment]
WilhelmSK is adding decimal point because of the gauge you chose.

n2k-signalk gets that info from pgn 129029, not 129540: https://github.com/SignalK/n2k-signalk/blob/master/pgns/129029.js#L17

**Comment by aplathan** [comment]
@sbender9 you're right about the WilhelmSK. I had "Generic Amps" selected because there is no dedicated gauge available for number of satellites. So perhaps this issue really belongs to instrumentpanel.

**Comment by tkurki** [comment]
Yes it does.
